eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8762
spring:
  application:
    name: service-hi

  ##zipkin 配置
  zipkin:
    base-url: http://127.0.0.1:9411
    sender:
      type: rabbit
  sleuth:
    sampler:
      probability: 1.0
  ##rabbitmq
  rabbitmq:
    username: rabbit
    password: rabbitmq
    host: 127.0.0.1
    port: 5672