eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
server:
  port: 8769
spring:
  application:
    name: service-zuul
    ##zipkin 配置
  zipkin:
    base-url: http://127.0.0.1:9411
    sender:
      type: rabbit
  sleuth:
    sampler:
      probability: 1.0
      ##rabbitmq
  rabbitmq:
    username: rabbit
    password: rabbitmq
    host: 127.0.0.1
    port: 5672
zuul:
  #ignored-services: provider-user          # 需要忽视的服务(配置后将不会被路由)
  routes:
    api-b:
      path: /api-b/**
      serviceId: service-feign
